# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Paladar' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Paladar
  pod 'Firebase', '~> 3.5'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'FirebaseAuth', '~> 3.0'
  pod 'Firebase/Storage'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Braintree’
  pod 'SWRevealViewController', '~> 2.3'
  pod 'Alamofire-SwiftyJSON'
  pod ‘SDWebImage’
end
